// src/constants/legal.ts

export type LegalBlock =
  | { type: "p"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "h"; text: string };

export type LegalSection = {
  title: string; 
  blocks: LegalBlock[];
};

export const TERMS_AND_CONDITIONS: LegalSection[] = [
  {
    title: "1. About Vinony",
    blocks: [
      {
        type: "p",
        text:
          'Vinony is a subscription-based AI SaaS platform that provides access to multiple third-party and proprietary artificial intelligence models and tools, including chat image generation, video generation, and task-based AI agents.',
      },
      {
        type: "p",
        text:
          'Vinony does not develop or control the underlying AI models. Outputs are generated by third-party providers and are provided "as is".',
      },
    ],
  },
  {
    title: "2. Eligibility and Account Registration",
    blocks: [
      {
        type: "ul",
        items: [
          "You must be at least 18 years old to use Vinony.",
          "You must provide accurate and complete account information.",
          "You are responsible for all activity under your account.",
          "Keep your login credentials secure.",
        ],
      },
      {
        type: "p",
        text:
          "Vinony reserves the right to suspend or terminate accounts that violate these Terms or applicable laws.",
      },
    ],
  },
  {
    title: "3. Subscriptions, Credits, and Payments",
    blocks: [
      { type: "h", text: "3.1 Subscription Plans" },
      {
        type: "p",
        text:
          "Vinony offers paid subscription plans that include a monthly allocation of credits. Subscription credits reset at the start of each billing cycle and do not rollover.",
      },

      { type: "h", text: "3.2 Credit Usage" },
      {
        type: "ul",
        items: [
          "Credits are required to use AI features.",
          "Credit costs vary depending on the model and task.",
          "Credit usage is displayed transparently before or after each generation where applicable.",
        ],
      },

      { type: "h", text: "3.3 Top-Up Credits" },
      {
        type: "ul",
        items: ["Top-up credits are purchased separately.", "Top-up credits do not expire."],
      },

      { type: "h", text: "3.4 Payments and Taxes" },
      {
        type: "p",
        text:
          "Payments are processed via Stripe. Applicable taxes, including VAT, are calculated at checkout.",
      },
    ],
  },
  {
    title: "4. Refund Policy",
    blocks: [
      { type: "p", text: "Vinony does not offer cash refunds." },
      {
        type: "p",
        text:
          "In exceptional cases, Vinony may issue credit-based refunds at its sole discretion. Refunded credits can only be used within the platform and cannot be exchanged for money.",
      },
    ],
  },
  {
    title: "5. Free Tier Usage",
    blocks: [
      { type: "p", text: "Free-tier accounts may have:" },
      {
        type: "ul",
        items: [
          "Limited credits",
          "Limited access to models",
          "Rate limits",
          "Watermarked outputs",
          "Restricted features (e.g. no video or agents)",
        ],
      },
      { type: "p", text: "Free-tier limits are subject to change at any time." },
    ],
  },
  {
    title: "6. Acceptable Use",
    blocks: [
      { type: "p", text: "You agree not to use Vinony for:" },
      {
        type: "ul",
        items: [
          "Illegal, harmful, or abusive activities",
          "Generating content that violates laws or third-party rights",
          "Attempting to reverse engineer or misuse the Service",
          "Circumventing usage limits or billing systems",
        ],
      },
      {
        type: "p",
        text: "Vinony may suspend or terminate access for violations without notice.",
      },
    ],
  },
  {
    title: "7. AI Output Disclaimer",
    blocks: [
      { type: "p", text: "AI-generated content may be inaccurate, incomplete, or misleading." },
      { type: "p", text: "You are solely responsible for:" },
      {
        type: "ul",
        items: [
          "Reviewing outputs before use",
          "Ensuring compliance with applicable laws",
          "How generated content is used or shared",
        ],
      },
      {
        type: "p",
        text:
          "Vinony makes no warranties regarding accuracy, reliability, or suitability of AI outputs.",
      },
    ],
  },
  {
    title: "8. Data Retention",
    blocks: [
      {
        type: "ul",
        items: [
          "AI generations and related data are retained for up to 90 days",
          "Data older than 90 days is automatically deleted",
          "Deleted data cannot be recovered",
        ],
      },
      { type: "p", text: "This policy applies to all users, including paid subscribers." },
    ],
  },
  {
    title: "9. Intellectual Property",
    blocks: [
      {
        type: "ul",
        items: [
          "Vinony owns the platform, branding, and original content.",
          "You retain rights to prompts you submit.",
          "You are responsible for ensuring you have rights to any content you upload.",
        ],
      },
      { type: "p", text: "AI-generated outputs may be subject to third-party provider terms." },
    ],
  },
  {
    title: "10. Service Availability",
    blocks: [
      {
        type: "p",
        text: "Vinony may modify, suspend, or discontinue any feature or model at any time without liability.",
      },
      {
        type: "p",
        text: "Specific AI models may be unavailable due to provider limitations, maintenance, or outages.",
      },
    ],
  },
  {
    title: "11. Limitation of Liability",
    blocks: [
      {
        type: "p",
        text:
          "To the maximum extent permitted by law, Vinony shall not be liable for indirect, incidental, or consequential damages arising from use of the Service.",
      },
      { type: "p", text: "Use of Vinony is at your own risk." },
    ],
  },
  {
    title: "12. Changes to These Terms",
    blocks: [
      {
        type: "p",
        text:
          "We may update these Terms from time to time. Continued use of the Service constitutes acceptance of the updated Terms.",
      },
    ],
  },
  {
    title: "13. Contact",
    blocks: [
      {
        type: "p",
        text: "For questions regarding these Terms, contact us at: support@vinony.com",
      },
    ],
  },
];

export const PRIVACY_POLICY: LegalSection[] = [
  {
    title: "1. Information We Collect",
    blocks: [
      { type: "h", text: "1.1 Account Information" },
      { type: "ul", items: ["Email address", "Authentication details", "Subscription and billing status"] },
      { type: "h", text: "1.2 Usage Data" },
      { type: "ul", items: ["AI prompts and outputs", "Model usage and credit consumption", "Interaction timestamps"] },
      { type: "h", text: "1.3 Payment Information" },
      {
        type: "p",
        text:
          "Payment details are processed by Stripe. Vinony does not store full payment card information.",
      },
    ],
  },
  {
    title: "2. How We Use Your Information",
    blocks: [
      { type: "p", text: "We use your information to:" },
      {
        type: "ul",
        items: [
          "Provide and operate the Service",
          "Process payments and subscriptions",
          "Track credit usage",
          "Improve platform performance",
          "Prevent fraud and abuse",
          "Comply with legal obligations",
        ],
      },
    ],
  },
  {
    title: "3. AI Data Processing",
    blocks: [
      { type: "p", text: "3.1 Subscription Plans" },
      {
        type: "ul",
        items: [
          "Prompts and inputs are sent to third-party AI providers to generate outputs.",
          "Vinony does not train its own AI models using your data.",
          "Data sent to providers is subject to their privacy policies.",
        ],
      },
    ],
  },
  {
    title: "4. Data Retention",
    blocks: [
      {
        type: "ul",
        items: [
          "AI generations and related data are retained for 90 days",
          "After 90 days, data is permanently deleted",
          "Billing and transaction records may be retained longer for legal compliance",
        ],
      },
    ],
  },
  {
    title: "5. Cookies and Tracking",
    blocks: [
      { type: "p", text: "Vinony uses cookies and similar technologies to:" },
      { type: "ul", items: ["Maintain sessions", "Analyze usage", "Improve performance"] },
      { type: "p", text: "You may control cookies through your browser settings." },
    ],
  },
  {
    title: "6. Data Sharing",
    blocks: [
      { type: "p", text: "We may share data with:" },
      {
        type: "ul",
        items: [
          "AI service providers (for generation)",
          "Payment processors (Stripe)",
          "Analytics and infrastructure providers",
        ],
      },
      { type: "p", text: "We do not sell personal data." },
    ],
  },
  {
    title: "7. Security",
    blocks: [
      {
        type: "p",
        text:
          "We implement reasonable technical and organizational measures to protect your data. However, no system is completely secure.",
      },
    ],
  },
  {
    title: "8. Your Rights",
    blocks: [
      { type: "p", text: "Depending on your location, you may have rights to:" },
      {
        type: "ul",
        items: [
          "Access your data",
          "Request correction or deletion",
          "Withdraw consent",
          "Lodge a complaint with a data authority",
        ],
      },
      { type: "p", text: "Requests can be made via support." },
    ],
  },
  {
    title: "9. International Data Transfers",
    blocks: [
      {
        type: "p",
        text:
          "Your data may be processed in countries outside your own. We take steps to ensure adequate safeguards are in place.",
      },
    ],
  },
  {
    title: "10. Changes to This Policy",
    blocks: [
      {
        type: "p",
        text:
          "We may update this Privacy Policy periodically. Continued use of Vinony means acceptance of the updated policy.",
      },
    ],
  },
  {
    title: "11. Contact",
    blocks: [
      {
        type: "p",
        text: "For questions regarding these Terms, contact us at: support@vinony.com",
      },
    ],
  },
];