export const PATH = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGETPASSWORD:"/forgot-password",
  RESETPASSWORD: "/reset-password",
  CONTACT:"/contact",
  // DASHBOARD: "/dashboard",
  // SIGNUP: "/signup",
  // JOBLISTING: "/jobListing",
  // Category: "/category",
  // JOBDETAIL: "/joblisting/:id",
  // SAVEDJOBS: "/savedJobs",
  // PROFILE: "/profile",
  // ExportCSV: "/exportCSV",
  // PRICING: "/pricing",
  // BILLING: "/checkout/:planId",
  // ENTERPRISE_INVOICE: "/enterprise/invoice/:token",
  // ENTERPRISE: "/enterprise",
  // Onboarding: "/onboarding",
  // VERIFY: "/verify",
  // Congratulations: "/congratulations",
  // FORGOT_PASSWORD: "/forgot-password",
  // RESET_PASSWORD: "/reset-password",
  // EMAIL_SETTING: "/setting/email",
  // COMPOSE: "/compose",
  // BILLING_CONFIRMATION: "/billing",
  // GOODBYE: "/goodbye",
} as const;